### ISSUE TITLE
[Suggestion] New Tab for Google Chrome

### ISSUE THREAD

**Issue by italoclone** [NerdyPepper/NerdyPepper.github.io#1]
I've converted the page to a Chrome extension to make it a new tab option.

just create a simple manifest.json like

```
{
  "name": "Personal New Tab",
  "description": "Custom new tab",
  "version": "0.1",
  "manifest_version": 2,
  
  "chrome_url_overrides" : {
    "newtab": "YourHtmlFile.html"
  }
  
}
```

you can take a look at mine https://github.com/italoclone/italoclone.github.io

**Comment by oppiliappan** [comment]
Sorry for the late reply. 

Will look into this ASAP.
